#!/usr/bin/env bash
set -euo pipefail

REPO_URL="https://github.com/diegosfb/dsfb-sdlc-v2.git"
DEST_DIR="${1:-antigravity-task-runner}"

echo "Cloning $REPO_URL into $DEST_DIR ..."
git clone "$REPO_URL" "$DEST_DIR"

cd "$DEST_DIR"

echo "Installing npm dependencies ..."
npm install

echo "Creating empty directories not tracked by git ..."
mkdir -p \
  ".agents/skills/google-gemini-api/rules" \
  "outputs"

echo "Creating placeholder files not in the git repo ..."
while IFS= read -r f; do
  mkdir -p "$(dirname "$f")"
  touch "$f"
done << 'FILELIST'
.agents/agents/architect-agent/architect-agent.md
.agents/agents/architect-agent/README.md
.agents/agents/architect-agent/references/architecture-template.md
.agents/agents/architect-agent/references/data-architecture-playbook.md
.agents/agents/architect-agent/subagents/blockchain-architect/blockchain-architect.md
.agents/agents/architect-agent/subagents/blockchain-architect/README.md
.agents/agents/architect-agent/subagents/data-architect/data-architect.md
.agents/agents/architect-agent/subagents/data-architect/README.md
.agents/agents/architect-agent/subagents/databricks-architect/databricks-architect.md
.agents/agents/architect-agent/subagents/databricks-architect/README.md
.agents/agents/architect-agent/subagents/embedded-architect/embedded-architect.md
.agents/agents/architect-agent/subagents/embedded-architect/README.md
.agents/agents/architect-agent/subagents/iot-architect/iot-architect.md
.agents/agents/architect-agent/subagents/iot-architect/README.md
.agents/agents/architect-agent/subagents/mobile-architect/mobile-architect.md
.agents/agents/architect-agent/subagents/mobile-architect/README.md
.agents/agents/ba-agent/ba-agent.md
.agents/agents/ba-agent/README.md
.agents/agents/ba-agent/references/intake-routing.md
.agents/agents/ba-agent/references/interviewing-playbook.md
.agents/agents/ba-agent/references/spec-template.md
.agents/agents/ba-agent/SpecCreator-Handbook/1- Mission and Output Contract.md
.agents/agents/ba-agent/SpecCreator-Handbook/2- Interview and Input Handling.md
.agents/agents/ba-agent/SpecCreator-Handbook/3- Specification Quality Bar.md
.agents/agents/code-review-agent/code-review-agent.md
.agents/agents/code-review-agent/README.md
.agents/agents/code-review-agent/references/infrastructure-security.md
.agents/agents/code-review-agent/references/penetration-testing.md
.agents/agents/code-review-agent/references/report-template.md
.agents/agents/code-review-agent/references/sast-tools.md
.agents/agents/code-review-agent/references/secret-scanning.md
.agents/agents/code-review-agent/references/vulnerability-patterns.md
.agents/agents/code-review-agent/review-references/common-issues.md
.agents/agents/code-review-agent/review-references/feedback-examples.md
.agents/agents/code-review-agent/review-references/report-template.md
.agents/agents/code-review-agent/review-references/review-checklist.md
.agents/agents/consultant-agent/subagents/explain-new-contributions/explain-new-contributions.md
.agents/agents/consultant-agent/subagents/explain-new-contributions/README.md
.agents/agents/deployment-agent/deployment-agent.md
.agents/agents/deployment-agent/README.md
.agents/agents/deployment-agent/references/devops-playbook.md
.agents/agents/deployment-agent/references/release_configuration_sample
.agents/agents/developer-agent/developer-agent.md
.agents/agents/developer-agent/README.md
.agents/agents/developer-agent/references/fix-application-playbook.md
.agents/agents/developer-agent/references/jira-execution-playbook.md
.agents/agents/developer-agent/subagents/be-developer/be-developer.md
.agents/agents/developer-agent/subagents/be-developer/README.md
.agents/agents/developer-agent/subagents/blockchain-developer/blockchain-developer.md
.agents/agents/developer-agent/subagents/blockchain-developer/README.md
.agents/agents/developer-agent/subagents/data-developer/data-developer.md
.agents/agents/developer-agent/subagents/data-developer/README.md
.agents/agents/developer-agent/subagents/databricks-developer/databricks-developer.md
.agents/agents/developer-agent/subagents/databricks-developer/README.md
.agents/agents/developer-agent/subagents/embedded-developer/embedded-developer.md
.agents/agents/developer-agent/subagents/embedded-developer/README.md
.agents/agents/developer-agent/subagents/fe-developer/fe-developer.md
.agents/agents/developer-agent/subagents/fe-developer/README.md
.agents/agents/developer-agent/subagents/iot-developer/iot-developer.md
.agents/agents/developer-agent/subagents/iot-developer/README.md
.agents/agents/developer-agent/subagents/mobile-developer/mobile-developer.md
.agents/agents/developer-agent/subagents/mobile-developer/README.md
.agents/agents/developer-agent/subagents/references/data-architecture-implementation.md
.agents/agents/developer-agent/subagents/references/database-engineering-playbook.md
.agents/agents/developer-agent/TODO.txt
.agents/agents/documentation-agent/agent.metadata.json
.agents/agents/documentation-agent/documentation-agent.md
.agents/agents/documentation-agent/README.md
.agents/agents/llm-judge-agent/llm-judge-agent.md
.agents/agents/llm-judge-agent/README.md
.agents/agents/llm-judge-agent/references/judging-rubrics.md
.agents/agents/obsidian-vault-agent/obsidian-vault-agent.md
.agents/agents/obsidian-vault-agent/README.md
.agents/agents/obsidian-vault-agent/references/vault-structure.md
.agents/agents/product-agent/product-agent.md
.agents/agents/product-agent/README.md
.agents/agents/product-agent/references/interviewing-discipline.md
.agents/agents/product-agent/references/prd-template.md
.agents/agents/product-agent/references/product-specialist-playbook.md
.agents/agents/project-planner-agent/jira-references/commands.md
.agents/agents/project-planner-agent/jira-references/jira-manager-playbook.md
.agents/agents/project-planner-agent/jira-references/mcp.md
.agents/agents/project-planner-agent/project-planner-agent.md
.agents/agents/project-planner-agent/README.md
.agents/agents/project-planner-agent/references/confirmation-template.md
.agents/agents/project-planner-agent/references/epic-template.md
.agents/agents/project-planner-agent/references/estimation-methodology.md
.agents/agents/project-planner-agent/references/execution-ordering.md
.agents/agents/project-planner-agent/references/issue-template.md
.agents/agents/project-planner-agent/references/jira-handoff.md
.agents/agents/sdlc-orchestrator/README.md
.agents/agents/sdlc-orchestrator/sdlc-orchestrator.md
.agents/agents/spec-validation-agent/README.md
.agents/agents/spec-validation-agent/spec-validation-agent.md
.agents/agents/spec-validation-agent/subagents/security-check-agent/README.md
.agents/agents/spec-validation-agent/subagents/security-check-agent/security-check-agent.md
.agents/agents/spec-validation-agent/subagents/spec-drift-checker/README.md
.agents/agents/spec-validation-agent/subagents/spec-drift-checker/spec-drift-checker.md
.agents/agents/spec-validation-agent/subagents/spec-red-team/README.md
.agents/agents/spec-validation-agent/subagents/spec-red-team/spec-red-team.md
.agents/agents/test-agent/README.md
.agents/agents/test-agent/references/test-generation-playbook.md
.agents/agents/test-agent/subagents/red-team-agent/README.md
.agents/agents/test-agent/subagents/red-team-agent/red-team-agent.md
.agents/agents/test-agent/test-agent.md
.agents/agents/ux-agent/README.md
.agents/agents/ux-agent/ux-agent.md
.agents/documentation/Agentic Platforms Info/agent-creation-guidelines.md
.agents/documentation/Agentic Platforms Info/Antigravity.md
.agents/documentation/Agentic Platforms Info/Claude.md
.agents/documentation/Agentic Platforms Info/codex-toml-definitions.md
.agents/documentation/Agentic Platforms Info/Codex.md
.agents/documentation/Agentic Platforms Info/evals info.md
.agents/documentation/Agentic Platforms Info/Gemini.md
.agents/documentation/context-budget-recommendations.md
.agents/documentation/TODO/Analyst Agent
.agents/documentation/TODO/Software Engineering Tutor.txt
.agents/documentation/TODO/Software Estimator.txt
.agents/skills/accessibility-runtime-tester/SKILL.md
.agents/skills/accessibility-runtime-tester/skill.metadata.json
.agents/skills/accessibility/SKILL.md
.agents/skills/accessibility/skill.metadata.json
.agents/skills/acquire-codebase-knowledge/assets/templates/ARCHITECTURE.md
.agents/skills/acquire-codebase-knowledge/assets/templates/CONCERNS.md
.agents/skills/acquire-codebase-knowledge/assets/templates/CONVENTIONS.md
.agents/skills/acquire-codebase-knowledge/assets/templates/INTEGRATIONS.md
.agents/skills/acquire-codebase-knowledge/assets/templates/STACK.md
.agents/skills/acquire-codebase-knowledge/assets/templates/STRUCTURE.md
.agents/skills/acquire-codebase-knowledge/assets/templates/TESTING.md
.agents/skills/acquire-codebase-knowledge/references/inquiry-checkpoints.md
.agents/skills/acquire-codebase-knowledge/references/stack-detection.md
.agents/skills/acquire-codebase-knowledge/scripts/scan.py
.agents/skills/acquire-codebase-knowledge/SKILL.md
.agents/skills/acquire-codebase-knowledge/skill.metadata.json
.agents/skills/agent-auditor/agents/openai.yaml
.agents/skills/agent-auditor/assets/agent-audit-report-template.md
.agents/skills/agent-auditor/assets/agent-workflow-template.md
.agents/skills/agent-auditor/assets/agents-catalog-template.md
.agents/skills/agent-auditor/references/functional-overlap-analysis.md
.agents/skills/agent-auditor/scripts/audit_agents.py
.agents/skills/agent-auditor/SKILL.md
.agents/skills/agent-auditor/skill.metadata.json
.agents/skills/agent-content-security/agents/openai.yaml
.agents/skills/agent-content-security/assets/security-baseline.example.json
.agents/skills/agent-content-security/references/threat-model.md
.agents/skills/agent-content-security/scripts/security_scan.py
.agents/skills/agent-content-security/SKILL.md
.agents/skills/agent-content-security/skill.metadata.json
.agents/skills/agents-harness-sync/agents/openai.yaml
.agents/skills/agents-harness-sync/documentation/canonical-agent-YAML-frontmatter.md
.agents/skills/agents-harness-sync/documentation/context-budget-recommendations.md
.agents/skills/agents-harness-sync/documentation/sample-agent-capacity-manager.md
.agents/skills/agents-harness-sync/documentation/sync-agent-readme.md
.agents/skills/agents-harness-sync/references/canonical-agent-template.md
.agents/skills/agents-harness-sync/scripts/codex-toml-converter.sh
.agents/skills/agents-harness-sync/scripts/context-budget.py
.agents/skills/agents-harness-sync/scripts/opencode-agent-converter.py
.agents/skills/agents-harness-sync/scripts/sync-agents.sh
.agents/skills/agents-harness-sync/scripts/validate_agent_format.py
.agents/skills/agents-harness-sync/SKILL.md
.agents/skills/agents-harness-sync/skill.metadata.json
.agents/skills/architecture-designer/references/adr-template.md
.agents/skills/architecture-designer/references/api-design-patterns.md
.agents/skills/architecture-designer/references/architectural-principles.md
.agents/skills/architecture-designer/references/architecture-analysis-patterns.md
.agents/skills/architecture-designer/references/architecture-patterns.md
.agents/skills/architecture-designer/references/authentication.md
.agents/skills/architecture-designer/references/caching.md
.agents/skills/architecture-designer/references/database-patterns.md
.agents/skills/architecture-designer/references/database-selection.md
.agents/skills/architecture-designer/references/example.md
.agents/skills/architecture-designer/references/jobs-queues.md
.agents/skills/architecture-designer/references/logging.md
.agents/skills/architecture-designer/references/nfr-checklist.md
.agents/skills/architecture-designer/references/patterns-implementation-playbook.md
.agents/skills/architecture-designer/references/rate-limiting.md
.agents/skills/architecture-designer/references/system-design-workflows.md
.agents/skills/architecture-designer/references/system-design.md
.agents/skills/architecture-designer/references/technology-decision-guide.md
.agents/skills/architecture-designer/scripts/architecture_diagram_generator.py
.agents/skills/architecture-designer/scripts/dependency_analyzer.py
.agents/skills/architecture-designer/scripts/project_architect.py
.agents/skills/architecture-designer/SKILL.md
.agents/skills/architecture-designer/skill.metadata.json
.agents/skills/autoresearch/references/fit-check.md
.agents/skills/autoresearch/references/loop-mechanics.md
.agents/skills/autoresearch/SKILL.md
.agents/skills/autoresearch/skill.metadata.json
.agents/skills/azure-pricing/references/COPILOT-STUDIO-RATES.md
.agents/skills/azure-pricing/references/COST-ESTIMATOR.md
.agents/skills/azure-pricing/references/REGIONS.md
.agents/skills/azure-pricing/references/SERVICE-NAMES.md
.agents/skills/azure-pricing/SKILL.md
.agents/skills/azure-pricing/skill.metadata.json
.agents/skills/bigquery-data-transfer-service/scripts/bigquery_dts.py
.agents/skills/bigquery-data-transfer-service/SKILL.md
.agents/skills/bigquery-data-transfer-service/skill.metadata.json
.agents/skills/bigquery-transformation-frameworks/references/dataform.md
.agents/skills/bigquery-transformation-frameworks/references/dbt.md
.agents/skills/bigquery-transformation-frameworks/SKILL.md
.agents/skills/bigquery-transformation-frameworks/skill.metadata.json
.agents/skills/brainstorm-experiments/assets/experiment_plan_template.md
.agents/skills/brainstorm-experiments/examples/ai-summarization-willingness-to-pay-experiment.md
.agents/skills/brainstorm-experiments/references/experiment-methods.md
.agents/skills/brainstorm-experiments/references/red-flags.md
.agents/skills/brainstorm-experiments/scripts/experiment_designer.py
.agents/skills/brainstorm-experiments/SKILL.md
.agents/skills/brainstorm-experiments/skill.metadata.json
.agents/skills/brainstorm-ideas/assets/ideation_workshop_template.md
.agents/skills/brainstorm-ideas/examples/b2b-onboarding-redesign-trio-session.md
.agents/skills/brainstorm-ideas/references/ideation-frameworks.md
.agents/skills/brainstorm-ideas/references/red-flags.md
.agents/skills/brainstorm-ideas/scripts/idea_scorer.py
.agents/skills/brainstorm-ideas/scripts/opportunity_tree_builder.py
.agents/skills/brainstorm-ideas/scripts/scamper_generator.py
.agents/skills/brainstorm-ideas/SKILL.md
.agents/skills/brainstorm-ideas/skill.metadata.json
.agents/skills/building-data-apps/examples/express_chat.ts
.agents/skills/building-data-apps/examples/fastapi_chat.py
.agents/skills/building-data-apps/examples/react_chat_panel.jsx
.agents/skills/building-data-apps/resources/chat_integration.md
.agents/skills/building-data-apps/resources/react_framework.md
.agents/skills/building-data-apps/resources/shared_design_system.md
.agents/skills/building-data-apps/resources/streamlit_framework.md
.agents/skills/building-data-apps/SKILL.md
.agents/skills/building-data-apps/skill.metadata.json
.agents/skills/business-idea-evaluator/SKILL.md
.agents/skills/business-idea-evaluator/skill.metadata.json
.agents/skills/business-investment-advisor/examples/opportunities.json
.agents/skills/business-investment-advisor/examples/portfolio.json
.agents/skills/business-investment-advisor/references/investment-frameworks.md
.agents/skills/business-investment-advisor/scripts/due_diligence_checklist.py
.agents/skills/business-investment-advisor/scripts/investment_screener.py
.agents/skills/business-investment-advisor/scripts/portfolio_analyzer.py
.agents/skills/business-investment-advisor/SKILL.md
.agents/skills/business-investment-advisor/skill.metadata.json
.agents/skills/business-plan-builder/SKILL.md
.agents/skills/business-plan-builder/skill.metadata.json
.agents/skills/ca-tax-advisor/references/user-profile.md
.agents/skills/ca-tax-advisor/SKILL.md
.agents/skills/ca-tax-advisor/skill.metadata.json
.agents/skills/channel-economics/references/channel-conflict-resolution.md
.agents/skills/channel-economics/references/channel-models-direct-partner-marketplace.md
.agents/skills/channel-economics/references/margin-and-tco-frameworks.md
.agents/skills/channel-economics/scripts/channel_margin_calculator.py
.agents/skills/channel-economics/scripts/channel_mix_optimizer.py
.agents/skills/channel-economics/scripts/partner_tier_economics.py
.agents/skills/channel-economics/SKILL.md
.agents/skills/channel-economics/skill.metadata.json
.agents/skills/cloud-architect/references/aws.md
.agents/skills/cloud-architect/references/azure.md
.agents/skills/cloud-architect/references/cost.md
.agents/skills/cloud-architect/references/gcp.md
.agents/skills/cloud-architect/references/multi-cloud.md
.agents/skills/cloud-architect/references/traffic-profile.md
.agents/skills/cloud-architect/SKILL.md
.agents/skills/cloud-architect/skill.metadata.json
.agents/skills/code-reviewer/references/common-issues.md
.agents/skills/code-reviewer/references/feedback-examples.md
.agents/skills/code-reviewer/references/report-template.md
.agents/skills/code-reviewer/references/review-checklist.md
.agents/skills/code-reviewer/SKILL.md
.agents/skills/code-reviewer/skill.metadata.json
.agents/skills/coding-standards/references/api-design.md
.agents/skills/coding-standards/references/code-smells.md
.agents/skills/coding-standards/references/performance.md
.agents/skills/coding-standards/references/project-organization.md
.agents/skills/coding-standards/references/react.md
.agents/skills/coding-standards/references/testing.md
.agents/skills/coding-standards/references/typescript-javascript.md
.agents/skills/coding-standards/SKILL.md
.agents/skills/coding-standards/skill.metadata.json
.agents/skills/contract-drafting-assistant/agents/openai.yaml
.agents/skills/contract-drafting-assistant/scripts/contract_comparison_analyzer.py
.agents/skills/contract-drafting-assistant/scripts/contract_completeness_checker.py
.agents/skills/contract-drafting-assistant/SKILL.md
.agents/skills/contract-drafting-assistant/skill.metadata.json
.agents/skills/customer-interview-script/assets/interview_script_template.md
.agents/skills/customer-interview-script/assets/question_bank.md
.agents/skills/customer-interview-script/examples/churn-investigation-filled-script.md
.agents/skills/customer-interview-script/references/interviewing-methodology-guide.md
.agents/skills/customer-interview-script/references/red-flags.md
.agents/skills/customer-interview-script/SKILL.md
.agents/skills/customer-interview-script/skill.metadata.json
.agents/skills/customer-success-manager/agents/openai.yaml
.agents/skills/customer-success-manager/assets/executive_business_review_template.md
.agents/skills/customer-success-manager/assets/expected_output.json
.agents/skills/customer-success-manager/assets/onboarding_checklist_template.md
.agents/skills/customer-success-manager/assets/qbr_template.md
.agents/skills/customer-success-manager/assets/sample_customer_data.json
.agents/skills/customer-success-manager/assets/success_plan_template.md
.agents/skills/customer-success-manager/references/cs-playbooks.md
.agents/skills/customer-success-manager/references/health-scoring-framework.md
.agents/skills/customer-success-manager/references/illustrative-metrics-benchmarks.md
.agents/skills/customer-success-manager/scripts/churn_risk_analyzer.py
.agents/skills/customer-success-manager/scripts/expansion_opportunity_scorer.py
.agents/skills/customer-success-manager/scripts/health_score_calculator.py
.agents/skills/customer-success-manager/SKILL.md
.agents/skills/customer-success-manager/skill.metadata.json
.agents/skills/dashboard-builder/agents/openai.yaml
.agents/skills/dashboard-builder/references/google-cloud-monitoring.md
.agents/skills/dashboard-builder/references/looker-studio.md
.agents/skills/dashboard-builder/references/operational-dashboards.md
.agents/skills/dashboard-builder/SKILL.md
.agents/skills/dashboard-builder/skill.metadata.json
.agents/skills/data-autocleaning/scripts/dataplex_scanner.py
.agents/skills/data-autocleaning/SKILL.md
.agents/skills/data-autocleaning/skill.metadata.json
.agents/skills/data-cost-governance/references/bigquery.md
.agents/skills/data-cost-governance/references/cost-spike-runbook.md
.agents/skills/data-cost-governance/references/cross-platform-finops.md
.agents/skills/data-cost-governance/references/databricks.md
.agents/skills/data-cost-governance/references/object-storage.md
.agents/skills/data-cost-governance/references/snowflake.md
.agents/skills/data-cost-governance/SKILL.md
.agents/skills/data-cost-governance/skill.metadata.json
.agents/skills/data-governance/references/access-control.md
.agents/skills/data-governance/references/catalogs.md
.agents/skills/data-governance/references/classification-and-privacy.md
.agents/skills/data-governance/references/compliance-and-erasure.md
.agents/skills/data-governance/references/data-contracts.md
.agents/skills/data-governance/references/lineage.md
.agents/skills/data-governance/references/ownership-and-operating-model.md
.agents/skills/data-governance/SKILL.md
.agents/skills/data-governance/skill.metadata.json
.agents/skills/data-modeling/references/data-vault.md
.agents/skills/data-modeling/references/dimensional-modeling.md
.agents/skills/data-modeling/references/model-review-checklist.md
.agents/skills/data-modeling/references/model-selection.md
.agents/skills/data-modeling/references/relational-modeling.md
.agents/skills/data-modeling/references/schema-evolution.md
.agents/skills/data-modeling/SKILL.md
.agents/skills/data-modeling/skill.metadata.json
.agents/skills/data-quality/references/dbt-testing.md
.agents/skills/data-quality/references/great-expectations.md
.agents/skills/data-quality/references/incident-response.md
.agents/skills/data-quality/references/observability-and-anomalies.md
.agents/skills/data-quality/references/quality-model.md
.agents/skills/data-quality/references/slos-and-alerting.md
.agents/skills/data-quality/references/soda.md
.agents/skills/data-quality/SKILL.md
.agents/skills/data-quality/skill.metadata.json
.agents/skills/data-scraper/agents/openai.yaml
.agents/skills/data-scraper/references/implementation-guide.md
.agents/skills/data-scraper/SKILL.md
.agents/skills/data-scraper/skill.metadata.json
.agents/skills/data-security-compliance/references/audit-trails.md
.agents/skills/data-security-compliance/references/breach-and-cross-border-response.md
.agents/skills/data-security-compliance/references/ccpa-cpra.md
.agents/skills/data-security-compliance/references/classification-and-control-selection.md
.agents/skills/data-security-compliance/references/encryption-and-key-management.md
.agents/skills/data-security-compliance/references/gdpr-and-data-subject-rights.md
.agents/skills/data-security-compliance/references/retention-and-legal-holds.md
.agents/skills/data-security-compliance/references/tokenization.md
.agents/skills/data-security-compliance/SKILL.md
.agents/skills/data-security-compliance/skill.metadata.json
.agents/skills/database-design/references/database-selection.md
.agents/skills/database-design/references/indexing.md
.agents/skills/database-design/references/migrations.md
.agents/skills/database-design/references/optimization.md
.agents/skills/database-design/references/orm-selection.md
.agents/skills/database-design/references/schema-design.md
.agents/skills/database-design/scripts/schema_validator.py
.agents/skills/database-design/SKILL.md
.agents/skills/database-design/skill.metadata.json
.agents/skills/database-migrations/SKILL.md
.agents/skills/database-migrations/skill.metadata.json
.agents/skills/database-optimizer/references/index-strategies.md
.agents/skills/database-optimizer/references/monitoring-analysis.md
.agents/skills/database-optimizer/references/mysql-tuning.md
.agents/skills/database-optimizer/references/postgresql-tuning.md
.agents/skills/database-optimizer/references/query-optimization.md
.agents/skills/database-optimizer/SKILL.md
.agents/skills/database-optimizer/skill.metadata.json
.agents/skills/delivery-capacity-planner/agents/openai.yaml
.agents/skills/delivery-capacity-planner/references/geo-framework.md
.agents/skills/delivery-capacity-planner/references/input-schema.md
.agents/skills/delivery-capacity-planner/references/seniority-guidance.md
.agents/skills/delivery-capacity-planner/references/team-archetypes.md
.agents/skills/delivery-capacity-planner/SKILL.md
.agents/skills/delivery-capacity-planner/skill.metadata.json
.agents/skills/design-system/SKILL.md
.agents/skills/design-system/skill.metadata.json
.agents/skills/developing-with-bigquery/resources/ai-evaluate.md
.agents/skills/developing-with-bigquery/resources/ai-forecast.md
.agents/skills/developing-with-bigquery/resources/ai-generate-embedding.md
.agents/skills/developing-with-bigquery/resources/ai-generate-table.md
.agents/skills/developing-with-bigquery/resources/BIGFRAMES.md
.agents/skills/developing-with-bigquery/resources/BQML.md
.agents/skills/developing-with-bigquery/resources/ml-contribution-analysis.md
.agents/skills/developing-with-bigquery/resources/OPTIMIZATION.md
.agents/skills/developing-with-bigquery/resources/remote-models.md
.agents/skills/developing-with-bigquery/resources/vector-search.md
.agents/skills/developing-with-bigquery/SKILL.md
.agents/skills/developing-with-bigquery/skill.metadata.json
.agents/skills/development-estimation/references/clarification-output-schema.md
.agents/skills/development-estimation/references/clarification-preflight.md
.agents/skills/development-estimation/references/estimate.md
.agents/skills/development-estimation/references/man-hour-estimation.md
.agents/skills/development-estimation/scripts/write_clarifications.py
.agents/skills/development-estimation/SKILL.md
.agents/skills/development-estimation/skill.metadata.json
.agents/skills/diagnosing-bugs/agents/openai.yaml
.agents/skills/diagnosing-bugs/scripts/hitl-loop.template.sh
.agents/skills/diagnosing-bugs/SKILL.md
.agents/skills/diagnosing-bugs/skill.metadata.json
.agents/skills/discovering-gcp-data-assets/SKILL.md
.agents/skills/discovering-gcp-data-assets/skill.metadata.json
.agents/skills/doc-generator/references/documentation-guide.md
.agents/skills/doc-generator/SKILL.md
.agents/skills/doc-generator/skill.metadata.json
.agents/skills/drawio-skill/data/databricks-icons.json
.agents/skills/drawio-skill/data/lobe-icons.json
.agents/skills/drawio-skill/data/SHAPE-INDEX-NOTICE.md
.agents/skills/drawio-skill/data/shape-index.json.gz
.agents/skills/drawio-skill/references/autolayout.md
.agents/skills/drawio-skill/references/databricks.md
.agents/skills/drawio-skill/references/derasterize.md
.agents/skills/drawio-skill/references/diagram-types.md
.agents/skills/drawio-skill/references/live-infra.md
.agents/skills/drawio-skill/references/mermaid-authoring.md
.agents/skills/drawio-skill/references/pr-bot.md
.agents/skills/drawio-skill/references/shapes.md
.agents/skills/drawio-skill/references/style-extraction.md
.agents/skills/drawio-skill/references/style-presets.md
.agents/skills/drawio-skill/references/toolbox.md
.agents/skills/drawio-skill/references/troubleshooting.md
.agents/skills/drawio-skill/references/tubemap.md
.agents/skills/drawio-skill/references/xml-authoring.md
.agents/skills/drawio-skill/scripts/aiicons.py
.agents/skills/drawio-skill/scripts/autolayout.py
.agents/skills/drawio-skill/scripts/buildup.py
.agents/skills/drawio-skill/scripts/c4.py
.agents/skills/drawio-skill/scripts/ciimports.py
.agents/skills/drawio-skill/scripts/composeimports.py
.agents/skills/drawio-skill/scripts/compress.py
.agents/skills/drawio-skill/scripts/dbxicons.py
.agents/skills/drawio-skill/scripts/dockerimports.py
.agents/skills/drawio-skill/scripts/drawio2mermaid.py
.agents/skills/drawio-skill/scripts/drawio2pptx.py
.agents/skills/drawio-skill/scripts/drawiodiff.py
.agents/skills/drawio-skill/scripts/drawiohtml.py
.agents/skills/drawio-skill/scripts/edgeports.py
.agents/skills/drawio-skill/scripts/encode_drawio_url.py
.agents/skills/drawio-skill/scripts/explain.py
.agents/skills/drawio-skill/scripts/goimports.py
.agents/skills/drawio-skill/scripts/heatmap.py
.agents/skills/drawio-skill/scripts/jsimports.py
.agents/skills/drawio-skill/scripts/k8simports.py
.agents/skills/drawio-skill/scripts/openapiimports.py
.agents/skills/drawio-skill/scripts/prdiff.py
.agents/skills/drawio-skill/scripts/pyclasses.py
.agents/skills/drawio-skill/scripts/pyimports.py
.agents/skills/drawio-skill/scripts/raster2drawio.py
.agents/skills/drawio-skill/scripts/relabel.py
.agents/skills/drawio-skill/scripts/repair_png.py
.agents/skills/drawio-skill/scripts/restyle.py
.agents/skills/drawio-skill/scripts/runbook.py
.agents/skills/drawio-skill/scripts/rustimports.py
.agents/skills/drawio-skill/scripts/seqlayout.py
.agents/skills/drawio-skill/scripts/shapesearch.py
.agents/skills/drawio-skill/scripts/sqlerd.py
.agents/skills/drawio-skill/scripts/svgflow.py
.agents/skills/drawio-skill/scripts/tfimports.py
.agents/skills/drawio-skill/scripts/tfstate.py
.agents/skills/drawio-skill/scripts/timelapse.py
.agents/skills/drawio-skill/scripts/tubemap.py
.agents/skills/drawio-skill/scripts/validate.py
.agents/skills/drawio-skill/SKILL.md
.agents/skills/drawio-skill/skill.metadata.json
.agents/skills/drawio-skill/styles/built-in/colorblind-safe.json
.agents/skills/drawio-skill/styles/built-in/corporate.json
.agents/skills/drawio-skill/styles/built-in/dark.json
.agents/skills/drawio-skill/styles/built-in/default.json
.agents/skills/drawio-skill/styles/built-in/handdrawn.json
.agents/skills/drawio-skill/styles/schema.json
.agents/skills/e2e-testing/SKILL.md
.agents/skills/e2e-testing/skill.metadata.json
.agents/skills/ecommerce-advisor/agents/openai.yaml
.agents/skills/ecommerce-advisor/assets/unit_economics_template.json
.agents/skills/ecommerce-advisor/references/channel_strategy.md
.agents/skills/ecommerce-advisor/references/fulfillment_models.md
.agents/skills/ecommerce-advisor/scripts/ecom_unit_economics_calculator.py
.agents/skills/ecommerce-advisor/SKILL.md
.agents/skills/ecommerce-advisor/skill.metadata.json
.agents/skills/edge-architect/SKILL.md
.agents/skills/edge-architect/skill.metadata.json
.agents/skills/edtech-advisor/agents/openai.yaml
.agents/skills/edtech-advisor/assets/sdpa_inventory_template.md
.agents/skills/edtech-advisor/references/edtech_market_dynamics.md
.agents/skills/edtech-advisor/references/student_data_privacy.md
.agents/skills/edtech-advisor/scripts/student_data_compliance_checker.py
.agents/skills/edtech-advisor/SKILL.md
.agents/skills/edtech-advisor/skill.metadata.json
.agents/skills/enterprise-value-engineer/agents/openai.yaml
.agents/skills/enterprise-value-engineer/references/example-report.md
.agents/skills/enterprise-value-engineer/references/financial-formulas.md
.agents/skills/enterprise-value-engineer/references/input-schema.md
.agents/skills/enterprise-value-engineer/references/output-template.md
.agents/skills/enterprise-value-engineer/references/value-lever-mapping.md
.agents/skills/enterprise-value-engineer/SKILL.md
.agents/skills/enterprise-value-engineer/skill.metadata.json
.agents/skills/etl-elt-patterns/SKILL.md
.agents/skills/etl-elt-patterns/skill.metadata.json
.agents/skills/executive-advisor/agents/openai.yaml
.agents/skills/executive-advisor/references/ceo.md
.agents/skills/executive-advisor/references/executive-decision-council.md
.agents/skills/executive-advisor/references/finance.md
.agents/skills/executive-advisor/references/governance-ma.md
.agents/skills/executive-advisor/references/operations.md
.agents/skills/executive-advisor/references/people.md
.agents/skills/executive-advisor/references/product-revenue.md
.agents/skills/executive-advisor/references/startup-cto.md
.agents/skills/executive-advisor/references/technology.md
.agents/skills/executive-advisor/SKILL.md
.agents/skills/executive-advisor/skill.metadata.json
.agents/skills/explain-me/SKILL.md
.agents/skills/explain-me/skill.metadata.json
.agents/skills/financial-analyst/assets/dcf_analysis_template.md
.agents/skills/financial-analyst/assets/expected_output.json
.agents/skills/financial-analyst/assets/forecast_report_template.md
.agents/skills/financial-analyst/assets/sample_financial_data.json
.agents/skills/financial-analyst/assets/variance_report_template.md
.agents/skills/financial-analyst/references/financial-ratios-guide.md
.agents/skills/financial-analyst/references/forecasting-best-practices.md
.agents/skills/financial-analyst/references/valuation-methodology.md
.agents/skills/financial-analyst/scripts/budget_variance_analyzer.py
.agents/skills/financial-analyst/scripts/dcf_valuation.py
.agents/skills/financial-analyst/scripts/forecast_builder.py
.agents/skills/financial-analyst/scripts/ratio_calculator.py
.agents/skills/financial-analyst/SKILL.md
.agents/skills/financial-analyst/skill.metadata.json
.agents/skills/financial-workbook-builder/agents/openai.yaml
.agents/skills/financial-workbook-builder/references/financial_metrics.md
.agents/skills/financial-workbook-builder/references/formula_best_practices.md
.agents/skills/financial-workbook-builder/references/visualization_best_practices.md
.agents/skills/financial-workbook-builder/SKILL.md
.agents/skills/financial-workbook-builder/skill.metadata.json
.agents/skills/fintech-advisor/agents/openai.yaml
.agents/skills/fintech-advisor/assets/regulatory_architecture_template.md
.agents/skills/fintech-advisor/references/embedded_finance_patterns.md
.agents/skills/fintech-advisor/references/kyc_aml_basics.md
.agents/skills/fintech-advisor/references/license_vs_partner_playbook.md
.agents/skills/fintech-advisor/references/regulatory_landscape.md
.agents/skills/fintech-advisor/scripts/regulatory_trigger_checker.py
.agents/skills/fintech-advisor/SKILL.md
.agents/skills/fintech-advisor/skill.metadata.json
.agents/skills/founder-leadership-coaching/agents/openai.yaml
.agents/skills/founder-leadership-coaching/scripts/milestone_tracker.py
.agents/skills/founder-leadership-coaching/SKILL.md
.agents/skills/founder-leadership-coaching/skill.metadata.json
.agents/skills/fundamental-analysis/SKILL.md
.agents/skills/fundamental-analysis/skill.metadata.json
.agents/skills/g-e-technical-feasibility/assets/output-templates.md
.agents/skills/g-e-technical-feasibility/assets/validation-framework.md
.agents/skills/g-e-technical-feasibility/SKILL_DOCUMENTATION.md
.agents/skills/g-e-technical-feasibility/SKILL.md
.agents/skills/g-e-technical-feasibility/skill.metadata.json
.agents/skills/gcloud-auth-verification/SKILL.md
.agents/skills/gcloud-auth-verification/skill.metadata.json
.agents/skills/gcp-composer-troubleshooting/SKILL.md
.agents/skills/gcp-composer-troubleshooting/skill.metadata.json
.agents/skills/gcp-data-pipelines/SKILL.md
.agents/skills/gcp-data-pipelines/skill.metadata.json
.agents/skills/gcp-dataflow/resources/dataflow_diagnostics_reference.md
.agents/skills/gcp-dataflow/resources/dataflow_metrics_bigquery.md
.agents/skills/gcp-dataflow/resources/dataflow_metrics_core_job.md
.agents/skills/gcp-dataflow/resources/dataflow_metrics_pubsub.md
.agents/skills/gcp-dataflow/resources/dataflow_metrics_streaming_engine.md
.agents/skills/gcp-dataflow/resources/python_flex_template_reference.md
.agents/skills/gcp-dataflow/SKILL.md
.agents/skills/gcp-dataflow/skill.metadata.json
.agents/skills/gcp-pipeline-orchestration/references/orchestration-pipelines-schema.md
.agents/skills/gcp-pipeline-orchestration/scripts/trigger/airflow_trigger.py
.agents/skills/gcp-pipeline-orchestration/SKILL.md
.agents/skills/gcp-pipeline-orchestration/skill.metadata.json
.agents/skills/gcp-pipeline-resource-provisioning/references/gcp_pipeline_resource_provisioning_spec.md
.agents/skills/gcp-pipeline-resource-provisioning/SKILL.md
.agents/skills/gcp-pipeline-resource-provisioning/skill.metadata.json
.agents/skills/gcp-spark/resources/gcloud_dataproc.md
.agents/skills/gcp-spark/resources/ml_tasks.md
.agents/skills/gcp-spark/resources/read_write_data.md
.agents/skills/gcp-spark/resources/schema_direct_inspection.md
.agents/skills/gcp-spark/resources/spark_optimizations.md
.agents/skills/gcp-spark/SKILL.md
.agents/skills/gcp-spark/skill.metadata.json
.agents/skills/google-gemini-api/.claude-plugin/plugin.json
.agents/skills/google-gemini-api/references/code-execution.md
.agents/skills/google-gemini-api/references/context-caching.md
.agents/skills/google-gemini-api/references/function-calling.md
.agents/skills/google-gemini-api/references/generation-and-streaming.md
.agents/skills/google-gemini-api/references/grounding.md
.agents/skills/google-gemini-api/references/migration-errors-and-production.md
.agents/skills/google-gemini-api/references/models-and-limits.md
.agents/skills/google-gemini-api/references/multimodal-and-files.md
.agents/skills/google-gemini-api/references/quick-start-and-auth.md
.agents/skills/google-gemini-api/references/thinking-and-configuration.md
.agents/skills/google-gemini-api/scripts/check-versions.sh
.agents/skills/google-gemini-api/SKILL.md
.agents/skills/google-gemini-api/skill.metadata.json
.agents/skills/google-gemini-api/templates/streaming-chat.ts
.agents/skills/google-gemini-api/templates/text-generation-basic.ts
.agents/skills/google-gemini-embeddings/.claude-plugin/plugin.json
.agents/skills/google-gemini-embeddings/README.md
.agents/skills/google-gemini-embeddings/references/dimension-guide.md
.agents/skills/google-gemini-embeddings/references/model-comparison.md
.agents/skills/google-gemini-embeddings/references/rag-patterns.md
.agents/skills/google-gemini-embeddings/references/top-errors.md
.agents/skills/google-gemini-embeddings/references/vectorize-integration.md
.agents/skills/google-gemini-embeddings/rules/google-gemini-embeddings.md
.agents/skills/google-gemini-embeddings/scripts/check-versions.sh
.agents/skills/google-gemini-embeddings/SKILL.md
.agents/skills/google-gemini-embeddings/skill.metadata.json
.agents/skills/google-gemini-embeddings/templates/basic-embeddings.ts
.agents/skills/google-gemini-embeddings/templates/batch-embeddings.ts
.agents/skills/google-gemini-embeddings/templates/clustering.ts
.agents/skills/google-gemini-embeddings/templates/embeddings-fetch.ts
.agents/skills/google-gemini-embeddings/templates/package.json
.agents/skills/google-gemini-embeddings/templates/rag-with-vectorize.ts
.agents/skills/google-gemini-embeddings/templates/semantic-search.ts
.agents/skills/google-gemini-file-search/.claude-plugin/plugin.json
.agents/skills/google-gemini-file-search/LICENSE
.agents/skills/google-gemini-file-search/PROJECT_STATUS.md
.agents/skills/google-gemini-file-search/README.md
.agents/skills/google-gemini-file-search/references/chunking-and-metadata.md
.agents/skills/google-gemini-file-search/references/cost-quota-and-cleanup.md
.agents/skills/google-gemini-file-search/references/errors-and-troubleshooting.md
.agents/skills/google-gemini-file-search/references/querying-and-citations.md
.agents/skills/google-gemini-file-search/references/README.md
.agents/skills/google-gemini-file-search/references/setup-and-lifecycle.md
.agents/skills/google-gemini-file-search/references/testing-and-integration.md
.agents/skills/google-gemini-file-search/references/upload-and-indexing.md
.agents/skills/google-gemini-file-search/scripts/create-store.ts
.agents/skills/google-gemini-file-search/scripts/README.md
.agents/skills/google-gemini-file-search/SKILL.md
.agents/skills/google-gemini-file-search/skill.metadata.json
.agents/skills/google-gemini-file-search/templates/README.md
.agents/skills/grill-me/SKILL.md
.agents/skills/grill-me/skill.metadata.json
.agents/skills/grill-with-docs/ADR-FORMAT.md
.agents/skills/grill-with-docs/CONTEXT-FORMAT.md
.agents/skills/grill-with-docs/SKILL.md
.agents/skills/grill-with-docs/skill.metadata.json
.agents/skills/handoff/docs/readme.md
.agents/skills/handoff/scripts/write_handoff.py
.agents/skills/handoff/SKILL.md
.agents/skills/handoff/skill.metadata.json
.agents/skills/harvesting-meeting-context/evals/evals.json
.agents/skills/harvesting-meeting-context/install-dependencies.sh
.agents/skills/harvesting-meeting-context/references/phase-a-environment-setup.md
.agents/skills/harvesting-meeting-context/references/phase-b-preprocessing.md
.agents/skills/harvesting-meeting-context/references/phase-c-transcription.md
.agents/skills/harvesting-meeting-context/references/phase-d-extraction-analysis.md
.agents/skills/harvesting-meeting-context/references/phase-e-output-assembly.md
.agents/skills/harvesting-meeting-context/references/repair-and-integration.md
.agents/skills/harvesting-meeting-context/references/state-and-output-contracts.md
.agents/skills/harvesting-meeting-context/SKILL.md
.agents/skills/harvesting-meeting-context/skill.metadata.json
.agents/skills/healthtech-advisor/agents/openai.yaml
.agents/skills/healthtech-advisor/assets/hipaa_scope_template.md
.agents/skills/healthtech-advisor/references/fda_samd_basics.md
.agents/skills/healthtech-advisor/references/gtm_patterns.md
.agents/skills/healthtech-advisor/references/hipaa_basics.md
.agents/skills/healthtech-advisor/references/value_based_care_primer.md
.agents/skills/healthtech-advisor/scripts/phi_scope_checker.py
.agents/skills/healthtech-advisor/SKILL.md
.agents/skills/healthtech-advisor/skill.metadata.json
.agents/skills/humanizer/SKILL.md
.agents/skills/humanizer/skill.metadata.json
.agents/skills/identify-assumptions/assets/assumption_map_template.md
.agents/skills/identify-assumptions/examples/shared-dashboards-assumption-mapping.md
.agents/skills/identify-assumptions/references/assumption-mapping-guide.md
.agents/skills/identify-assumptions/references/red-flags.md
.agents/skills/identify-assumptions/scripts/assumption_tracker.py
.agents/skills/identify-assumptions/SKILL.md
.agents/skills/identify-assumptions/skill.metadata.json
.agents/skills/investor-materials/SKILL.md
.agents/skills/investor-materials/skill.metadata.json
.agents/skills/investor-outreach/SKILL.md
.agents/skills/investor-outreach/skill.metadata.json
.agents/skills/jira-project-creation/SKILL.md
.agents/skills/jira-project-creation/skill.metadata.json
.agents/skills/job-application-resume/agents/openai.yaml
.agents/skills/job-application-resume/assets/tailored_resume_template.md
.agents/skills/job-application-resume/references/application-system-formatting.md
.agents/skills/job-application-resume/references/bullet_rewrite_patterns.md
.agents/skills/job-application-resume/scripts/job_description_term_matcher.py
.agents/skills/job-application-resume/SKILL.md
.agents/skills/job-application-resume/skill.metadata.json
.agents/skills/leads-qualification/agents/openai.yaml
.agents/skills/leads-qualification/assets/icp_schema.json
.agents/skills/leads-qualification/references/icp_framework.md
.agents/skills/leads-qualification/scripts/lead_qualifier.py
.agents/skills/leads-qualification/SKILL.md
.agents/skills/leads-qualification/skill.metadata.json
.agents/skills/leads-qualification/tests/test_lead_qualifier.py
.agents/skills/leads-researcher/agents/openai.yaml
.agents/skills/leads-researcher/assets/account-brief-template.md
.agents/skills/leads-researcher/SKILL.md
.agents/skills/leads-researcher/skill.metadata.json
.agents/skills/llm-application-dev-langchain/SKILL.md
.agents/skills/llm-application-dev-langchain/skill.metadata.json
.agents/skills/log-generation/agents/openai.yaml
.agents/skills/log-generation/references/cloud-aws.md
.agents/skills/log-generation/references/cloud-gcp.md
.agents/skills/log-generation/references/schema.md
.agents/skills/log-generation/references/stack-dotnet.md
.agents/skills/log-generation/references/stack-java.md
.agents/skills/log-generation/references/stack-node.md
.agents/skills/log-generation/references/stack-python.md
.agents/skills/log-generation/references/stack-react.md
.agents/skills/log-generation/scripts/generate_log_plan.py
.agents/skills/log-generation/SKILL.md
.agents/skills/log-generation/skill.metadata.json
.agents/skills/ma-playbook/agents/openai.yaml
.agents/skills/ma-playbook/scripts/due_diligence_tracker.py
.agents/skills/ma-playbook/scripts/integration_planner.py
.agents/skills/ma-playbook/scripts/synergy_calculator.py
.agents/skills/ma-playbook/SKILL.md
.agents/skills/ma-playbook/skill.metadata.json
.agents/skills/marketplace-advisor/agents/openai.yaml
.agents/skills/marketplace-advisor/assets/marketplace_metrics_template.json
.agents/skills/marketplace-advisor/references/marketplace_dynamics.md
.agents/skills/marketplace-advisor/references/take_rate_design.md
.agents/skills/marketplace-advisor/scripts/marketplace_health_scorer.py
.agents/skills/marketplace-advisor/SKILL.md
.agents/skills/marketplace-advisor/skill.metadata.json
.agents/skills/medical-bill-price-review/agents/openai.yaml
.agents/skills/medical-bill-price-review/references/output-example.md
.agents/skills/medical-bill-price-review/references/pricing-sources.md
.agents/skills/medical-bill-price-review/SKILL.md
.agents/skills/medical-bill-price-review/skill.metadata.json
.agents/skills/meeting-insights/agents/openai.yaml
.agents/skills/meeting-insights/assets/meeting-analysis-template.md
.agents/skills/meeting-insights/assets/recap_template.md
.agents/skills/meeting-insights/references/insight_extraction_patterns.md
.agents/skills/meeting-insights/scripts/transcript_analyzer.py
.agents/skills/meeting-insights/SKILL.md
.agents/skills/meeting-insights/skill.metadata.json
.agents/skills/meeting-insights/tests/test_transcript_analyzer.py
.agents/skills/microservices-architect/references/communication.md
.agents/skills/microservices-architect/references/data.md
.agents/skills/microservices-architect/references/decomposition.md
.agents/skills/microservices-architect/references/observability.md
.agents/skills/microservices-architect/references/patterns.md
.agents/skills/microservices-architect/SKILL.md
.agents/skills/microservices-architect/skill.metadata.json
.agents/skills/morgan-stanley-ta/SKILL.md
.agents/skills/morgan-stanley-ta/skill.metadata.json
.agents/skills/no-mistakes/SKILL.md
.agents/skills/no-mistakes/skill.metadata.json
.agents/skills/observability-monitoring/references/alerting-rules.md
.agents/skills/observability-monitoring/references/application-profiling.md
.agents/skills/observability-monitoring/references/capacity-planning.md
.agents/skills/observability-monitoring/references/dashboards.md
.agents/skills/observability-monitoring/references/opentelemetry.md
.agents/skills/observability-monitoring/references/performance-testing.md
.agents/skills/observability-monitoring/references/prometheus-metrics.md
.agents/skills/observability-monitoring/references/structured-logging.md
.agents/skills/observability-monitoring/SKILL.md
.agents/skills/observability-monitoring/skill.metadata.json
.agents/skills/partnerships-architect/agents/openai.yaml
.agents/skills/partnerships-architect/references/partner-program-design.md
.agents/skills/partnerships-architect/references/partnership-deal-structures.md
.agents/skills/partnerships-architect/references/partnership-types.md
.agents/skills/partnerships-architect/scripts/partner_evaluation_scorer.py
.agents/skills/partnerships-architect/scripts/partner_program_designer.py
.agents/skills/partnerships-architect/scripts/partnership_roi_modeler.py
.agents/skills/partnerships-architect/SKILL.md
.agents/skills/partnerships-architect/skill.metadata.json
.agents/skills/partnerships-architect/tests/test_partnership_tools.py
.agents/skills/pitch-deck-builder/agents/openai.yaml
.agents/skills/pitch-deck-builder/references/data-visualization-guide.md
.agents/skills/pitch-deck-builder/references/narrative-frameworks.md
.agents/skills/pitch-deck-builder/references/pitch-deck-best-practices.md
.agents/skills/pitch-deck-builder/SKILL.md
.agents/skills/pitch-deck-builder/skill.metadata.json
.agents/skills/pitch-deck-reviewer/agents/openai.yaml
.agents/skills/pitch-deck-reviewer/assets/deck-review-report-template.md
.agents/skills/pitch-deck-reviewer/scripts/deck_structure_scorer.py
.agents/skills/pitch-deck-reviewer/SKILL.md
.agents/skills/pitch-deck-reviewer/skill.metadata.json
.agents/skills/pitch-deck-reviewer/tests/test_deck_structure_diagnostic.py
.agents/skills/playwright-expert/references/api-mocking.md
.agents/skills/playwright-expert/references/configuration.md
.agents/skills/playwright-expert/references/debugging-flaky.md
.agents/skills/playwright-expert/references/page-object-model.md
.agents/skills/playwright-expert/references/selectors-locators.md
.agents/skills/playwright-expert/SKILL.md
.agents/skills/playwright-expert/skill.metadata.json
.agents/skills/postman-test-scripts/SKILL.md
.agents/skills/postman-test-scripts/skill.metadata.json
.agents/skills/pre-mortem/assets/pre_mortem_template.md
.agents/skills/pre-mortem/examples/shared-dashboards-v1-pre-mortem.md
.agents/skills/pre-mortem/references/pre-mortem-guide.md
.agents/skills/pre-mortem/references/red-flags.md
.agents/skills/pre-mortem/scripts/risk_categorizer.py
.agents/skills/pre-mortem/SKILL.md
.agents/skills/pre-mortem/skill.metadata.json
.agents/skills/presales-engineering/agents/openai.yaml
.agents/skills/presales-engineering/assets/demo_script_template.md
.agents/skills/presales-engineering/assets/poc_scorecard_template.md
.agents/skills/presales-engineering/assets/sample_rfp_data.json
.agents/skills/presales-engineering/assets/technical_proposal_template.md
.agents/skills/presales-engineering/references/competitive-positioning-framework.md
.agents/skills/presales-engineering/references/poc-best-practices.md
.agents/skills/presales-engineering/references/rfp-response-guide.md
.agents/skills/presales-engineering/scripts/competitive_matrix_builder.py
.agents/skills/presales-engineering/scripts/poc_planner.py
.agents/skills/presales-engineering/scripts/rfp_response_analyzer.py
.agents/skills/presales-engineering/SKILL.md
.agents/skills/presales-engineering/skill.metadata.json
.agents/skills/press-release/agents/openai.yaml
.agents/skills/press-release/assets/press-release-template.md
.agents/skills/press-release/references/executive-appointment-example.md
.agents/skills/press-release/references/partnership-example.md
.agents/skills/press-release/references/product-launch-example.md
.agents/skills/press-release/references/style-guide.md
.agents/skills/press-release/SKILL.md
.agents/skills/press-release/skill.metadata.json
.agents/skills/pricing-strategy/agents/openai.yaml
.agents/skills/pricing-strategy/references/price-increases-and-diagnostics.md
.agents/skills/pricing-strategy/references/pricing-pages-and-positioning.md
.agents/skills/pricing-strategy/references/research-and-price-points.md
.agents/skills/pricing-strategy/references/value-metrics-and-packaging.md
.agents/skills/pricing-strategy/scripts/price_increase_modeler.py
.agents/skills/pricing-strategy/scripts/price_sensitivity_calculator.py
.agents/skills/pricing-strategy/scripts/pricing_model_analyzer.py
.agents/skills/pricing-strategy/SKILL.md
.agents/skills/pricing-strategy/skill.metadata.json
.agents/skills/prompt-engineer/references/scoring-rubric.md
.agents/skills/prompt-engineer/references/techniques.md
.agents/skills/prompt-engineer/references/templates.md
.agents/skills/prompt-engineer/SKILL.md
.agents/skills/prompt-engineer/skill.metadata.json
.agents/skills/proposal-and-sow-writer/agents/openai.yaml
.agents/skills/proposal-and-sow-writer/scripts/proposal_cost_estimator.py
.agents/skills/proposal-and-sow-writer/SKILL.md
.agents/skills/proposal-and-sow-writer/skill.metadata.json
.agents/skills/proptech-advisor/agents/openai.yaml
.agents/skills/proptech-advisor/assets/proptech_segment_assessment.md
.agents/skills/proptech-advisor/references/mls_and_brokerage.md
.agents/skills/proptech-advisor/references/proptech_segments.md
.agents/skills/proptech-advisor/scripts/market_segment_classifier.py
.agents/skills/proptech-advisor/SKILL.md
.agents/skills/proptech-advisor/skill.metadata.json
.agents/skills/prototype/LOGIC.md
.agents/skills/prototype/SKILL.md
.agents/skills/prototype/skill.metadata.json
.agents/skills/prototype/UI.md
.agents/skills/rag-architect/SKILL.md
.agents/skills/rag-architect/skill.metadata.json
.agents/skills/recruiting-capacity-planner/agents/openai.yaml
.agents/skills/recruiting-capacity-planner/references/bench-matching.md
.agents/skills/recruiting-capacity-planner/references/recruiting-benchmarks.md
.agents/skills/recruiting-capacity-planner/references/schemas.md
.agents/skills/recruiting-capacity-planner/SKILL.md
.agents/skills/recruiting-capacity-planner/skill.metadata.json
.agents/skills/revenue-operations/assets/expected_output.json
.agents/skills/revenue-operations/assets/forecast_report_template.md
.agents/skills/revenue-operations/assets/gtm_dashboard_template.md
.agents/skills/revenue-operations/assets/pipeline_review_template.md
.agents/skills/revenue-operations/assets/sample_forecast_data.json
.agents/skills/revenue-operations/assets/sample_gtm_data.json
.agents/skills/revenue-operations/assets/sample_pipeline_data.json
.agents/skills/revenue-operations/references/gtm-efficiency-benchmarks.md
.agents/skills/revenue-operations/references/pipeline-management-framework.md
.agents/skills/revenue-operations/references/revops-metrics-guide.md
.agents/skills/revenue-operations/scripts/forecast_accuracy_tracker.py
.agents/skills/revenue-operations/scripts/gtm_efficiency_calculator.py
.agents/skills/revenue-operations/scripts/pipeline_analyzer.py
.agents/skills/revenue-operations/SKILL.md
.agents/skills/revenue-operations/skill.metadata.json
.agents/skills/secrets-management/references/application-integration.md
.agents/skills/secrets-management/references/cloud-secret-managers.md
.agents/skills/secrets-management/references/fundamentals-and-architecture.md
.agents/skills/secrets-management/references/hashicorp-vault.md
.agents/skills/secrets-management/references/rotation-and-revocation.md
.agents/skills/secrets-management/SKILL.md
.agents/skills/secrets-management/skill.metadata.json
.agents/skills/senior-data-engineer/references/data_modeling_patterns.md
.agents/skills/senior-data-engineer/references/data_pipeline_architecture.md
.agents/skills/senior-data-engineer/references/dataops_best_practices.md
.agents/skills/senior-data-engineer/scripts/data_quality_validator.py
.agents/skills/senior-data-engineer/scripts/etl_performance_optimizer.py
.agents/skills/senior-data-engineer/scripts/pipeline_orchestrator.py
.agents/skills/senior-data-engineer/SKILL.md
.agents/skills/senior-data-engineer/skill.metadata.json
.agents/skills/senior-fullstack/references/architecture_patterns.md
.agents/skills/senior-fullstack/references/development_workflows.md
.agents/skills/senior-fullstack/references/tech_stack_guide.md
.agents/skills/senior-fullstack/scripts/code_quality_analyzer.py
.agents/skills/senior-fullstack/scripts/project_scaffolder.py
.agents/skills/senior-fullstack/SKILL.md
.agents/skills/senior-fullstack/skill.metadata.json
.agents/skills/simplify/agents/openai.yaml
.agents/skills/simplify/LICENSE
.agents/skills/simplify/SKILL.md
.agents/skills/simplify/skill.metadata.json
.agents/skills/skill-auditor/assets/skill-audit-report-template.md
.agents/skills/skill-auditor/references/functional-overlap-analysis.md
.agents/skills/skill-auditor/scripts/audit_skill.py
.agents/skills/skill-auditor/scripts/check_overlap.py
.agents/skills/skill-auditor/scripts/generate_report.py
.agents/skills/skill-auditor/scripts/trace_skill_usage.py
.agents/skills/skill-auditor/SKILL.md
.agents/skills/skill-auditor/skill.metadata.json
.agents/skills/snowflake-development/references/snowflake-best-practices.md
.agents/skills/snowflake-development/scripts/snowflake_query_helper.py
.agents/skills/snowflake-development/SKILL.md
.agents/skills/snowflake-development/skill.metadata.json
.agents/skills/solo-founder-prioritization/SKILL.md
.agents/skills/solo-founder-prioritization/skill.metadata.json
.agents/skills/storypoints-council/agents/openai.yaml
.agents/skills/storypoints-council/references/council-protocol.md
.agents/skills/storypoints-council/references/estimation-methodology.md
.agents/skills/storypoints-council/references/local-cli-config.md
.agents/skills/storypoints-council/references/local-cli-overview.md
.agents/skills/storypoints-council/references/openrouter-config.md
.agents/skills/storypoints-council/references/openrouter-estimation-methodology.md
.agents/skills/storypoints-council/references/openrouter-overview.md
.agents/skills/storypoints-council/resources/historical/tasks.csv
.agents/skills/storypoints-council/resources/new-tasks.csv
.agents/skills/storypoints-council/resources/openrouter-historical-tasks.csv
.agents/skills/storypoints-council/resources/openrouter-new-tasks.csv
.agents/skills/storypoints-council/scripts/council.py
.agents/skills/storypoints-council/scripts/local_council.py
.agents/skills/storypoints-council/scripts/openrouter_council.py
.agents/skills/storypoints-council/SKILL.md
.agents/skills/storypoints-council/skill.metadata.json
.agents/skills/storypoints-council/storypoints-council.conf.example
.agents/skills/storypoints-council/storypoints-council.local.conf.example
.agents/skills/storypoints-council/storypoints-council.openrouter.conf.example
.agents/skills/streaming-specialist/references/apache-flink.md
.agents/skills/streaming-specialist/references/apache-kafka.md
.agents/skills/streaming-specialist/references/aws-kinesis.md
.agents/skills/streaming-specialist/references/backpressure-and-stream-to-lake.md
.agents/skills/streaming-specialist/references/spark-structured-streaming.md
.agents/skills/streaming-specialist/references/streaming-fundamentals.md
.agents/skills/streaming-specialist/SKILL.md
.agents/skills/streaming-specialist/skill.metadata.json
.agents/skills/system-requirements-estimation/agents/openai.yaml
.agents/skills/system-requirements-estimation/references/latency-numbers.md
.agents/skills/system-requirements-estimation/scripts/estimate_capacity.py
.agents/skills/system-requirements-estimation/SKILL.md
.agents/skills/system-requirements-estimation/skill.metadata.json
.agents/skills/tdd/agents/openai.yaml
.agents/skills/tdd/mocking.md
.agents/skills/tdd/SKILL.md
.agents/skills/tdd/skill.metadata.json
.agents/skills/tdd/tests.md
.agents/skills/terraform-engineer/references/best-practices.md
.agents/skills/terraform-engineer/references/module-patterns.md
.agents/skills/terraform-engineer/references/providers.md
.agents/skills/terraform-engineer/references/state-management.md
.agents/skills/terraform-engineer/references/testing.md
.agents/skills/terraform-engineer/SKILL.md
.agents/skills/terraform-engineer/skill.metadata.json
.agents/skills/thought-leadership-writing/agents/openai.yaml
.agents/skills/thought-leadership-writing/SKILL.md
.agents/skills/thought-leadership-writing/skill.metadata.json
.agents/skills/to-spec/agents/openai.yaml
.agents/skills/to-spec/SKILL.md
.agents/skills/to-spec/skill.metadata.json
.agents/skills/to-tickets/agents/openai.yaml
.agents/skills/to-tickets/SKILL.md
.agents/skills/to-tickets/skill.metadata.json
.agents/skills/ui-design-system/references/component-architecture.md
.agents/skills/ui-design-system/references/developer-handoff.md
.agents/skills/ui-design-system/references/responsive-calculations.md
.agents/skills/ui-design-system/references/token-generation.md
.agents/skills/ui-design-system/scripts/design_token_generator.py
.agents/skills/ui-design-system/SKILL.md
.agents/skills/ui-design-system/skill.metadata.json
.agents/skills/ui-designer/SKILL.md
.agents/skills/ui-designer/skill.metadata.json
.agents/skills/ux-researcher-designer/references/example-personas.md
.agents/skills/ux-researcher-designer/references/journey-mapping-guide.md
.agents/skills/ux-researcher-designer/references/persona-methodology.md
.agents/skills/ux-researcher-designer/references/research-synthesis.md
.agents/skills/ux-researcher-designer/references/usability-testing-frameworks.md
.agents/skills/ux-researcher-designer/scripts/persona_generator.py
.agents/skills/ux-researcher-designer/SKILL.md
.agents/skills/ux-researcher-designer/skill.metadata.json
.agents/skills/vtu-estimator/agents/openai.yaml
.agents/skills/vtu-estimator/assets/calculation-input.example.json
.agents/skills/vtu-estimator/assets/client-proposal-template.md
.agents/skills/vtu-estimator/assets/internal-appendix-template.md
.agents/skills/vtu-estimator/references/artifacts.md
.agents/skills/vtu-estimator/references/execution-standard.md
.agents/skills/vtu-estimator/references/experts.md
.agents/skills/vtu-estimator/references/offerings.md
.agents/skills/vtu-estimator/references/pricing.md
.agents/skills/vtu-estimator/scripts/calculate_vtu.py
.agents/skills/vtu-estimator/SKILL.md
.agents/skills/vtu-estimator/skill.metadata.json
.agents/skills/websocket-engineer/references/alternatives.md
.agents/skills/websocket-engineer/references/patterns.md
.agents/skills/websocket-engineer/references/protocol.md
.agents/skills/websocket-engineer/references/scaling.md
.agents/skills/websocket-engineer/references/security.md
.agents/skills/websocket-engineer/SKILL.md
.agents/skills/websocket-engineer/skill.metadata.json
.claude/settings.local.json
.codex/agents/architect-agent.toml
.codex/agents/ba-agent.toml
.codex/agents/be-developer.toml
.codex/agents/blockchain-architect.toml
.codex/agents/blockchain-developer.toml
.codex/agents/code-review-agent.toml
.codex/agents/data-architect.toml
.codex/agents/data-developer.toml
.codex/agents/databricks-architect.toml
.codex/agents/databricks-developer.toml
.codex/agents/deployment-agent.toml
.codex/agents/developer-agent.toml
.codex/agents/embedded-architect.toml
.codex/agents/embedded-developer.toml
.codex/agents/explain-new-contributions.toml
.codex/agents/fe-developer.toml
.codex/agents/iot-architect.toml
.codex/agents/iot-developer.toml
.codex/agents/llm-judge-agent.toml
.codex/agents/mobile-architect.toml
.codex/agents/mobile-developer.toml
.codex/agents/obsidian-vault-agent.toml
.codex/agents/product-agent.toml
.codex/agents/project-planner-agent.toml
.codex/agents/red-team-agent.toml
.codex/agents/sdlc-orchestrator.toml
.codex/agents/security-check-agent.toml
.codex/agents/spec-drift-checker.toml
.codex/agents/spec-red-team.toml
.codex/agents/spec-validation-agent.toml
.codex/agents/test-agent.toml
.codex/agents/ux-agent.toml
.env
docs/__backlog/Feature add ADLC folder
docs/__backlog/Feature add input page for BA
docs/__backlog/Feature add input page for Developer
docs/__backlog/Feature add input page for Estimator
docs/__backlog/Feature add input page for Plan Execution
docs/__backlog/Feature add input page for Product Designer
docs/__backlog/Feature add input page for Solution Architect
docs/backlog/story-adlc-agents-section.md
docs/backlog/story-assistance-agents.md
docs/backlog/story-mark-backlog-item-as-completed.md
docs/backlog/story-take-backlog-item-assign.md
docs/backlog/story-us-002-repository-actions.md
docs/backlog/US-001 - hide litellm.txt
docs/review Notes/Dependencies.md
docs/review Notes/deployment.md
docs/review Notes/github-actions-suggestions.md
docs/review Notes/tools-workflow.md
docs/review Notes/workflow-demo.md
docs/review Notes/working-rules.md
docs/Sample/specs-sample/SPEC_001.md
docs/Sample/superpowers/plans/2026-05-07-light-agentic-harness-command.md
docs/Sample/superpowers/plans/2026-05-10-audit-secrets-and-variables.md
docs/Sample/superpowers/specs/2026-05-07-light-agentic-harness-command-design.md
docs/Sample/superpowers/specs/2026-05-10-audit-secrets-and-variables-design.md
docs/TODO/improve.md
docs/TODO/TODO.txt
docs/vault/Action-Log/2026-09-18.md
docs/vault/Action-Log/2026-09-19.md
docs/vault/Action-Log/2026-09-20.md
docs/vault/Action-Log/2026-09-21.md
docs/vault/Notes/20260918T063158895333Z-implementation-note-resolved-all-outstanding-merge-conflicts-using-the-incoming-new-version.md
docs/vault/Notes/20260918T081954623527Z-implementation-note-us-001-hides-the-run-litellm-openai-tree-item.md
docs/vault/Notes/20260919T083324523232Z-design-decision-architect-agent-uses-mode-specific-architecture-input-contracts.md
docs/vault/Notes/20260919T083751754922Z-design-decision-architect-agent-discovers-workflow-configuration-with-safe-defaults.md
docs/vault/Notes/20260919T085014072664Z-implementation-note-architect-agent-settings-diagram-shows-both-architecture-modes.md
docs/vault/Notes/20260919T085844545224Z-implementation-note-architect-agent-settings-diagram-omits-automatic-configuration.md
docs/vault/Notes/20260919T090244392445Z-implementation-note-architect-diagram-distinguishes-architecture-modes-and-required-inputs.md
docs/vault/Notes/20260919T092000717934Z-implementation-note-architect-mode-is-auto-detected-with-override-and-conditional-inputs.md
docs/vault/Notes/20260919T093142497454Z-implementation-note-architect-agent-uses-one-unified-visible-input-contract.md
docs/vault/Notes/20260919T094515285748Z-implementation-note-architect-specification-input-now-appears-first.md
docs/vault/Notes/20260919T095052202188Z-design-decision-personal-use-is-free-while-all-organizational-use-requires-a-paid-license.md
docs/vault/Notes/20260919T095257637254Z-design-decision-ba-agent-exposes-two-optional-context-inputs.md
docs/vault/Notes/20260919T095951439222Z-implementation-note-readme-licensing-summary-matches-the-personal-use-license.md
docs/vault/Notes/20260919T100302620801Z-problem-vsce-packaging-failed-because-package-metadata-used-a-placeholder-repository-url.md
docs/vault/Notes/20260919T101207921878Z-design-decision-product-agent-uses-canonical-source-and-evidence-inputs.md
docs/vault/Notes/20260919T101554032241Z-design-decision-architect-outputs-are-grouped-in-the-architecture-folder.md
docs/vault/Notes/20260919T102021964088Z-implementation-note-product-definition-label-was-shortened.md
docs/vault/Notes/20260919T102607294587Z-implementation-note-architecture-review-now-matches-the-architect-agent-contract.md
docs/vault/Notes/20260919T103202486203Z-design-decision-ux-agent-exposes-its-complete-experience-context.md
docs/vault/Notes/20260919T104922755559Z-design-decision-ux-outputs-are-the-design-document-and-updated-specifications.md
docs/vault/Notes/20260919T105405914591Z-implementation-note-ux-agent-page-labels-its-two-outputs-clearly.md
docs/vault/Notes/20260919T105806038710Z-design-decision-ux-design-package-contains-the-design-document-and-wireframes.md
docs/vault/Notes/20260919T110430125023Z-design-decision-project-planner-consumes-optional-ux-design-package.md
docs/vault/Notes/20260919T114056752695Z-design-decision-project-planner-outputs-dependency-sequenced-user-stories.md
docs/vault/Notes/20260919T114639738498Z-design-decision-create-tests-consumes-dependency-sequenced-user-stories.md
docs/vault/Notes/20260919T115254590840Z-implementation-note-create-tests-labels-dependency-sequenced-stories-as-backlog.md
docs/vault/Notes/20260919T115517063784Z-design-decision-create-tests-writes-tests-inside-src.md
docs/vault/Notes/20260919T120555167468Z-implementation-note-project-planner-labels-dependency-sequenced-stories-as-backlog.md
docs/vault/Notes/20260919T121409733929Z-design-decision-create-tests-accepts-a-backlog-or-one-user-story-specification.md
docs/vault/Notes/20260919T121839919269Z-design-decision-coding-agent-outputs-source-code-inside-src.md
docs/vault/Notes/20260919T122153620211Z-design-decision-targeted-create-tests-source-overrides-backlog.md
docs/vault/Notes/20260919T123013838922Z-design-decision-coding-agent-accepts-backlog-or-targeted-implementation-scope.md
docs/vault/Notes/20260919T123321436926Z-implementation-note-coding-agent-shows-conditional-required-input-group.md
docs/vault/Notes/20260919T123500492178Z-implementation-note-coding-agent-diagram-includes-pull-request-output.md
docs/vault/Notes/20260919T124124435168Z-implementation-note-coding-agent-pull-request-output-is-nested-under-src.md
docs/vault/Notes/20260919T124431550160Z-design-decision-code-review-screen-consumes-pull-request-and-outputs-pr-merge.md
docs/vault/Notes/20260919T125227923500Z-implementation-note-coding-agent-description-states-downstream-orchestration-responsibility.md
docs/vault/Notes/20260919T130148437705Z-design-decision-deployment-agent-uses-a-release-manifest-with-optional-lifecycle-scripts.md
docs/vault/Notes/20260919T130322385354Z-implementation-note-spec-validation-and-documentation-agents-are-hidden-from-the-sidebar.md
docs/vault/Notes/20260919T130749018950Z-design-decision-sdlc-orchestrator-accepts-only-the-user-request-and-shows-delegation.md
docs/vault/Notes/20260919T130841950264Z-design-decision-adlc-agent-pages-use-a-top-right-run-action.md
docs/vault/Notes/20260919T130932793730Z-implementation-note-adlc-agent-tree-icons-use-red.md
docs/vault/Notes/20260919T131325612171Z-implementation-note-deployment-agent-page-includes-styled-lifecycle-diagram.md
docs/vault/Notes/20260919T131750335854Z-implementation-note-developer-workflow-now-invokes-documentation-agent-after-tests-pass.md
docs/vault/Notes/20260919T133434295974Z-implementation-note-every-agent-contract-now-has-a-companion-readme.md
docs/vault/Notes/20260919T134002139924Z-implementation-note-task-runner-view-name-no-longer-duplicates-the-container-title.md
docs/vault/Notes/20260919T141111740645Z-implementation-note-agentic-workflow-documentation-synchronized-with-current-agent-contracts.md
docs/vault/Notes/20260920T062542951741Z-implementation-note-renamed-agentic-library-deployment-actions-to-installation-actions.md
docs/vault/Notes/20260920T062847508713Z-implementation-note-grouped-backlog-actions-under-backlog-management.md
docs/vault/Notes/20260920T063804472547Z-implementation-note-added-auxiliary-agents-and-skills-sidebar-section.md
docs/vault/Notes/20260920T064201132590Z-implementation-note-moved-jira-project-selection-into-backlog-management.md
docs/vault/Notes/20260920T064318240141Z-design-decision-matched-auxiliary-section-to-feature-estimator-color.md
docs/vault/Notes/20260920T064522162233Z-implementation-note-grouped-version-increment-actions.md
docs/vault/Notes/20260920T070503307023Z-implementation-note-changed-increment-versions-group-icon.md
docs/vault/Notes/20260920T070642886919Z-implementation-note-added-obsidian-vault-visualization-action.md
docs/vault/Notes/20260920T070837143839Z-implementation-note-added-adlc-framework-manual-action.md
docs/vault/Notes/20260920T071202924150Z-problem-fixed-obsidian-launcher-script-resolution.md
docs/vault/Notes/20260920T073503674125Z-implementation-note-improved-personal-use-license-text.md
docs/vault/Notes/20260920T110209484436Z-implementation-note-adlc-framework-manual-opens-rendered-mermaid-preview.md
docs/vault/Notes/20260920T110758540479Z-implementation-note-adlc-workflow-diagram-starts-from-project-description.md
docs/vault/Notes/20260920T110956482572Z-implementation-note-removed-stale-vsix-package-include.md
docs/vault/Notes/20260920T111341414818Z-implementation-note-adlc-manual-opens-static-mermaid-preview-file.md
docs/vault/Notes/20260920T111801097242Z-implementation-note-simplified-adlc-workflow-diagram-return-edges.md
docs/vault/Notes/20260920T112258602928Z-implementation-note-sdlc-orchestrator-matches-adlc-workflow-diagram.md
docs/vault/Notes/20260920T112554831424Z-implementation-note-adlc-design-document-synced-to-workflow-diagram.md
docs/vault/Notes/20260920T112734514380Z-implementation-note-adlc-manual-opens-design-document-in-markdown-preview.md
docs/vault/Notes/20260920T113423585523Z-implementation-note-adlc-manual-keeps-design-preview-open.md
docs/vault/Notes/20260920T114402248640Z-implementation-note-added-agent-page-diagrams-to-sdlc-docs.md
docs/vault/Notes/20260920T115143219060Z-implementation-note-adlc-design-clarifies-parent-agent-ownership.md
docs/vault/Notes/20260921T040811235068Z-implementation-note-updated-context-budget-recommendations-with-actual-analyzer-path-and-current-hig.md
docs/vault/Notes/20260921T041237448490Z-implementation-note-updated-agentic-workflows-docs-to-match-project-description-workflow.md
docs/vault/Notes/20260921T041750899514Z-implementation-note-updated-review-notes-for-adlc-workflow-consistency.md
docs/vault/Notes/20260921T042335842412Z-implementation-note-workflows-tree-now-lists-workspace-agents-workflows.md
docs/vault/Notes/20260921T043004746671Z-implementation-note-skills-tree-now-includes-shared-and-multi-harness-skill-sources.md
docs/vault/Notes/20260921T043652889962Z-implementation-note-agents-tree-now-includes-shared-and-multi-harness-agent-sources.md
docs/vault/Notes/20260921T045129345146Z-implementation-note-synchronized-agents-skills-catalog-with-local-project-definitions.md
docs/vault/Notes/20260921T045940199025Z-implementation-note-ignored-local-setup-directories.md
docs/vault/Notes/20260921T050948050154Z-implementation-note-renamed-and-simplified-taskrunner-settings-page.md
docs/vault/Notes/20260921T052226362459Z-implementation-note-documented-workspace-project-path-usage-in-task-runner-help.md
docs/vault/Notes/20260921T052710688784Z-implementation-note-changed-default-terminal-names-to-taskrunner-labels.md
docs/vault/Notes/20260921T053326288476Z-implementation-note-removed-obsolete-taskrunner-root-path-setting.md
evals/cases/initial.jsonl
evals/cases/workflow.jsonl
evals/README.md
evals/run-evals.py
Knowhow/Anthropic settings.md
Knowhow/Antigravity workflows/approve_pull_request/WORKFLOW.md
Knowhow/Antigravity workflows/create_feature_branch/WORKFLOW.md
Knowhow/Antigravity workflows/create_pull_request/WORKFLOW.md
Knowhow/Antigravity workflows/terminate_pull_request/WORKFLOW.md
Knowhow/Check What you have available.txt
Knowhow/Compiling & Installing.md
Knowhow/Folder .agent.md
Knowhow/PullRequest SOP.md
Knowhow/Security.md
package-lock.json
package.json
project-setup.sh
README.md
Resources/AGENTS.md
Resources/CLAUDE.md
Resources/cloud-architect.svg
Resources/cloud-architect/references/aws.md
Resources/cloud-architect/references/azure.md
Resources/cloud-architect/references/cost.md
Resources/cloud-architect/references/gcp.md
Resources/cloud-architect/references/multi-cloud.md
Resources/cloud-architect/references/traffic-profile.md
Resources/cloud-architect/SKILL.md
Resources/estimator/SKILL.md
Resources/explain-me.svg
Resources/explain-me/SKILL.md
Resources/feature-estimator-red.svg
Resources/grill-me/SKILL.md
Resources/help.md
Resources/images.png
Resources/jira-project-creation log.txt
Resources/jira-project-creation/SKILL.md
Resources/messagebot.jpg
Resources/ovalagent.png
Resources/project-templates.json
Resources/prompts/update-agents-md.md
Resources/sop- as check list.md
Resources/sop.md
Resources/squarebot.svg
Resources/taskrunner.jpg
Resources/taskrunner.png
Resources/taskrunner.svg
Resources/type-name.md
Resources/v4.9.4-testing-checklist.md
scripts/helper-scripts/eval-capture.py
src/adlcAgents.ts
src/agenticHarnessCommand.ts
src/agenticHarnessSkill.ts
src/agentRunCommand.ts
src/assignBacklogItemToAgent.ts
src/autocommit_changes.sh
src/autocommit_revert.sh
src/backlogItem.ts
src/backlogItemCompleted.ts
src/bundledProjectSkill.ts
src/businessAnalyst.ts
src/checkout_branch.sh
src/cloudArchitectReview.ts
src/commit-push-tag.sh
src/create_feature_branch.sh
src/create_pull_requrest.sh
src/create-repo.sh
src/deployAgenticLib.ts
src/developer.ts
src/estimator.ts
src/explainMe.ts
src/extension.ts
src/featureEstimator.ts
src/git_remote_fallback.sh
src/git.ts
src/grillMe.ts
src/infer_jira_issue_link.js
src/init-repo.sh
src/jira.ts
src/jiraProjectHarness.ts
src/jiraRunner.ts
src/logger.ts
src/merge_branch_to_main.sh
src/mergeReviewPrompt.ts
src/planExecution.ts
src/productDesigner.ts
src/projectTemplates.ts
src/pull_remote_and_merge.sh
src/resourceProvider.ts
src/run-claude-workflow.sh
src/scripts.ts
src/secrets-audit.ts
src/settings.ts
src/shellUtils.ts
src/solutionArchitect.ts
src/Switch-ClaudeCode-Model.sh
src/sync-view-name.js
src/terminal.ts
src/treeProvider.ts
src/update-agent-setup.sh
src/update-agentic-workspace.sh
src/updateProjectConfig.ts
src/utils.ts
src/workspace-setup.sh
tests/adlcAgents.test.js
tests/agenticHarnessCommand.test.js
tests/agenticHarnessSkill.test.js
tests/agentRunCommand.test.js
tests/assignBacklogItemToAgent.test.js
tests/backlogItem.test.js
tests/backlogItemCompleted.test.js
tests/businessAnalyst.test.js
tests/cloudArchitectReview.test.js
tests/createFeatureBranch.test.js
tests/createPullRequest.test.js
tests/deployAgenticLib.test.js
tests/deployAgenticLibToProjectScript.test.js
tests/developer.test.js
tests/estimator.test.js
tests/explainMe.test.js
tests/extension.test.js
tests/featureEstimator.test.js
tests/git.test.js
tests/gitRemoteFallback.test.js
tests/grillMe.test.js
tests/jira.test.js
tests/jiraProjectHarness.test.js
tests/logger.test.js
tests/mergeReviewPrompt.test.js
tests/planExecution.test.js
tests/productDesigner.test.js
tests/projectTemplates.test.js
tests/pullRemoteAndMerge.test.js
tests/resourceProvider.test.js
tests/scripts.test.js
tests/secretsAudit.test.js
tests/settings.test.js
tests/solutionArchitect.test.js
tests/syncViewName.test.js
tests/terminal.test.js
tests/treeProvider.test.js
tests/updateProjectConfig.test.js
tests/utils.test.js
FILELIST

echo "Setup complete. Project is in ./$DEST_DIR"
