#!/usr/bin/env bash
# Convert canonical Markdown agents and nested subagents into Codex-compatible
# TOML adapters.
# nested subagents under .agents/agents. Codex discovers project agents from
# .codex/agents; it discovers skills directly from .agents/skills.

set -euo pipefail

SOURCE_AGENTS=".agents/agents"
CODEX_AGENTS=".codex/agents"
GENERATED_MARKER="# Generated by .agents/skills/agents-harness-sync/scripts/codex-toml-converter.sh"
LEGACY_GENERATED_MARKER="# Generated by scripts/link-agents-into-codex.sh"

if [[ ! -d "$SOURCE_AGENTS" ]]; then
  echo "No $SOURCE_AGENTS directory found here. Nothing to generate." >&2
  exit 1
fi

mkdir -p "$CODEX_AGENTS"

generated=0
unchanged=0
skipped=0

toml_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

while IFS= read -r -d '' agent_file; do
  filename="$(basename "$agent_file" .md)"
  parent_dir="$(dirname "$agent_file")"
  parent_name="$(basename "$parent_dir")"

  if [[ "$parent_dir" == "$SOURCE_AGENTS" ]]; then
    [[ "$filename" == "agents-catalog" || "$filename" == "README" ]] && continue
  elif [[ "$parent_name" != "$filename" ]]; then
    continue
  fi

  name="$(sed -n '/^---$/,/^---$/s/^name:[[:space:]]*//p' "$agent_file" | head -n 1)"
  description="$(sed -n '/^---$/,/^---$/s/^description:[[:space:]]*//p' "$agent_file" | head -n 1)"

  name="${name#\"}"
  name="${name%\"}"
  name="${name#\'}"
  name="${name%\'}"
  [[ -n "$name" ]] || name="$filename"

  description="${description#\"}"
  description="${description%\"}"
  description="${description#\'}"
  description="${description%\'}"
  description="${description%%\\n*}"
  [[ -n "$description" ]] || description="Codex adapter for the canonical $name agent."

  adapter="$CODEX_AGENTS/$name.toml"
  temp_adapter="$(mktemp "${TMPDIR:-/tmp}/codex-agent-adapter.XXXXXX")"
  trap 'rm -f "$temp_adapter"' EXIT

  {
    printf '%s\n' "$GENERATED_MARKER"
    printf '# Source: %s\n' "$agent_file"
    printf 'name = "%s"\n' "$(toml_escape "$name")"
    printf 'description = "%s"\n' "$(toml_escape "$description")"
    printf "developer_instructions = '''\n"
    printf 'Follow the canonical agent definition below. Resolve its relative paths from the directory containing the source file.\n\n'
    printf '%s\n' "$(<"$agent_file")"
    printf "'''\n"
  } > "$temp_adapter"

  if [[ -e "$adapter" ]] \
    && ! grep -Fqx "$GENERATED_MARKER" "$adapter" \
    && ! grep -Fqx "$LEGACY_GENERATED_MARKER" "$adapter"; then
    echo "SKIP: $adapter exists and was not generated by this script -- resolve manually." >&2
    skipped=$((skipped + 1))
    rm -f "$temp_adapter"
    trap - EXIT
    continue
  fi

  if [[ -f "$adapter" ]] && cmp -s "$temp_adapter" "$adapter"; then
    echo "OK (unchanged agent): $name"
    unchanged=$((unchanged + 1))
  else
    mv "$temp_adapter" "$adapter"
    echo "Generated agent: $name"
    generated=$((generated + 1))
  fi

  [[ -e "$temp_adapter" ]] && rm -f "$temp_adapter"
  trap - EXIT
done < <(find "$SOURCE_AGENTS" -type f -name '*.md' -print0)

echo
echo "Done. Generated: $generated, unchanged: $unchanged, skipped: $skipped."
echo "Skills remain in .agents/skills; workflows were not modified."

if [[ "$skipped" -gt 0 ]]; then
  echo "Some Codex agent adapters were skipped -- see SKIP lines above." >&2
  exit 1
fi
