#!/usr/bin/env python3
"""Generate OpenCode-native Markdown adapters from canonical agent definitions."""

import ctypes
import errno
import json
import os
import secrets
import stat
from pathlib import Path


SOURCE_ROOT = Path(".agents/agents")
TARGET_ROOT = Path(".opencode/agents")
GENERATED_MARKER = "# Generated by agents-harness-sync/opencode-agent-converter.py"
READ_ONLY_AGENTS = {
    "code-review-agent",
    "explain-me",
    "explain-new-contributions",
    "llm-judge-agent",
    "security-check-agent",
    "spec-drift-checker",
    "spec-red-team",
}
LIBC = ctypes.CDLL(None, use_errno=True)


def syscall_error(name):
    code = ctypes.get_errno()
    raise OSError(code, "{}: {}".format(name, os.strerror(code)))


def open_at(directory_fd, name, flags, mode=0o600):
    descriptor = LIBC.openat(directory_fd, os.fsencode(name), flags, mode)
    if descriptor < 0:
        syscall_error("openat")
    return descriptor


def readlink_at(directory_fd, name):
    buffer = ctypes.create_string_buffer(4096)
    size = LIBC.readlinkat(directory_fd, os.fsencode(name), buffer, len(buffer))
    if size < 0:
        syscall_error("readlinkat")
    return os.fsdecode(buffer.raw[:size])


def replace_at(directory_fd, source, destination):
    if LIBC.renameat(directory_fd, os.fsencode(source), directory_fd, os.fsencode(destination)) < 0:
        syscall_error("renameat")


def unlink_at(directory_fd, name):
    if LIBC.unlinkat(directory_fd, os.fsencode(name), 0) < 0:
        syscall_error("unlinkat")


def canonical_agents():
    for path in SOURCE_ROOT.rglob("*.md"):
        if path.parent == SOURCE_ROOT:
            if path.name in ("agents-catalog.md", "README.md"):
                continue
        elif path.parent.name != path.stem:
            continue
        yield path


def split_definition(path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError("{} has no YAML frontmatter".format(path))
    closing = text.find("\n---\n", 4)
    if closing < 0:
        raise ValueError("{} has unterminated YAML frontmatter".format(path))
    return text[4:closing], text[closing + 5 :]


def scalar(frontmatter, key, default=""):
    prefix = key + ":"
    for line in frontmatter.splitlines():
        if not line.startswith(prefix):
            continue
        value = line[len(prefix) :].strip()
        if value.startswith('"'):
            try:
                return str(json.loads(value))
            except ValueError:
                pass
        return value.strip("'\"") or default
    return default


def adapter(path):
    frontmatter, _body = split_definition(path)
    description = scalar(frontmatter, "description", "OpenCode adapter for {}".format(path.stem))
    role = scalar(frontmatter, "role")
    nested = "subagents" in path.relative_to(SOURCE_ROOT).parts
    mode = "subagent" if role == "subagent" or nested else "primary"
    sensitive_action = "deny" if path.stem in READ_ONLY_AGENTS else "ask"
    canonical_path = path.as_posix()
    canonical_directory = path.parent.as_posix()
    wrapper = """# OpenCode Canonical Agent Wrapper

Before responding to the user or performing domain work:

1. Read the canonical agent definition at `{}`.
2. Treat its YAML frontmatter and Markdown body as the authoritative operating contract for this invocation.
3. Resolve every relative reference from `{}`, the canonical agent directory—not from `.opencode/agents`.
4. Load referenced files only when the canonical contract requires them.
5. When the canonical contract delegates to a subagent by name or file path, invoke the matching OpenCode agent ID; that wrapper will load its own canonical definition.

The wrapper supplies only OpenCode compatibility metadata and safety permissions. The canonical file supplies the agent behavior, responsibilities, workflow, references, and delegation rules.
""".format(canonical_path, canonical_directory)
    return "---\n{}\ndescription: {}\nmode: {}\npermission:\n  \"*\": ask\n  read: allow\n  glob: allow\n  grep: allow\n  list: allow\n  lsp: allow\n  edit: {}\n  bash: {}\n  task: {}\n  external_directory: deny\n---\n\n{}".format(
        GENERATED_MARKER,
        json.dumps(description, ensure_ascii=False),
        mode,
        sensitive_action,
        sensitive_action,
        sensitive_action,
        wrapper,
    )


def validate_target_root():
    project_root = Path.cwd().resolve(strict=True)
    opencode_root = Path(".opencode")
    if opencode_root.is_symlink():
        raise ValueError(".opencode must not be a symlink")
    opencode_root.mkdir(parents=True, exist_ok=True)
    resolved_opencode = opencode_root.resolve(strict=True)
    if resolved_opencode.parent != project_root:
        raise ValueError(".opencode resolves outside the project root")
    if TARGET_ROOT.is_symlink():
        raise ValueError(".opencode/agents must not be a symlink")
    TARGET_ROOT.mkdir(parents=True, exist_ok=True)
    if TARGET_ROOT.resolve(strict=True).parent != resolved_opencode:
        raise ValueError("OpenCode target resolves outside .opencode")
    return os.open(str(TARGET_ROOT), os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)


def write_adapter(path, content, target_fd):
    destination_name = path.stem + ".md"
    destination = TARGET_ROOT / destination_name
    descriptor = None
    try:
        descriptor = open_at(target_fd, destination_name, os.O_RDONLY | os.O_NOFOLLOW)
    except OSError as error:
        if error.errno not in (errno.ENOENT, errno.ELOOP):
            raise
        destination_kind = "missing" if error.errno == errno.ENOENT else "symlink"
    else:
        destination_kind = "regular" if stat.S_ISREG(os.fstat(descriptor).st_mode) else "other"
    if destination_kind == "symlink":
        try:
            link = readlink_at(target_fd, destination_name)
            (TARGET_ROOT / link).resolve(strict=True).relative_to(SOURCE_ROOT.resolve(strict=True))
        except (OSError, ValueError):
            print("SKIP: {} is not a managed canonical-agent link".format(destination))
            return "skipped"
    elif destination_kind != "missing":
        if destination_kind != "regular":
            if descriptor is not None:
                os.close(descriptor)
            print("SKIP: {} is not a regular file".format(destination))
            return "skipped"
        with os.fdopen(descriptor, "r", encoding="utf-8", errors="replace") as handle:
            existing = handle.read()
        lines = existing.splitlines()
        if len(lines) < 2 or lines[0] != "---" or lines[1] != GENERATED_MARKER:
            print("SKIP: {} is manually maintained".format(destination))
            return "skipped"
        if existing == content:
            return "unchanged"
    temporary = ".opencode-agent-{}".format(secrets.token_hex(8))
    descriptor = open_at(
        target_fd, temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
        replace_at(target_fd, temporary, destination_name)
    finally:
        try:
            unlink_at(target_fd, temporary)
        except OSError as error:
            if error.errno != errno.ENOENT:
                raise
    return "generated"


def main():
    if not SOURCE_ROOT.is_dir():
        print("Missing {}".format(SOURCE_ROOT))
        return 2
    try:
        target_fd = validate_target_root()
    except (OSError, ValueError) as error:
        print("ERROR: {}".format(error))
        return 2
    counts = {"generated": 0, "unchanged": 0, "skipped": 0}
    names = set()
    try:
        for path in canonical_agents():
            if path.stem in names:
                print("ERROR: duplicate canonical agent {}".format(path.stem))
                return 2
            names.add(path.stem)
            try:
                result = write_adapter(path, adapter(path), target_fd)
            except (OSError, ValueError) as error:
                print("ERROR: {}".format(error))
                return 2
            counts[result] += 1
    finally:
        os.close(target_fd)
    print(
        "OpenCode adapters: generated={generated} unchanged={unchanged} skipped={skipped}".format(
            **counts
        )
    )
    return 1 if counts["skipped"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
