#!/usr/bin/env bash
set -euo pipefail

# Synchronize canonical agent definitions to harness-specific project folders.
# Supports flat definitions and the repository's <name>/<name>.md layout,
# including nested subagents. Supporting Markdown and the catalog are excluded.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
SOURCE_DIR="$PROJECT_ROOT/.agents/agents"
LOG_FILE="$PROJECT_ROOT/sync-agents.log"
CODEX_GENERATOR="$SCRIPT_DIR/codex-toml-converter.sh"
CODEX_GENERATED_MARKER="# Generated by .agents/skills/agents-harness-sync/scripts/codex-toml-converter.sh"
CODEX_LEGACY_MARKER="# Generated by scripts/link-agents-into-codex.sh"
DRY_RUN=0
CLEAN=0
ORIGINAL_ARGS=("$@")
ORIGINAL_ARG_COUNT=$#

usage() {
  cat <<'USAGE'
Usage: .agents/skills/agents-harness-sync/scripts/sync-agents.sh [--clean] [--dry-run]

  --clean    Remove links and adapters previously managed by this sync first.
  --dry-run  Report intended actions without changing harness targets.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --clean) CLEAN=1 ;;
    --dry-run) DRY_RUN=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

if [[ "${SYNC_AGENTS_LOGGING:-0}" != "1" ]]; then
  set +e
  if [[ "$ORIGINAL_ARG_COUNT" -gt 0 ]]; then
    SYNC_AGENTS_LOGGING=1 "$0" "${ORIGINAL_ARGS[@]}" 2>&1 | tee -a "$LOG_FILE"
  else
    SYNC_AGENTS_LOGGING=1 "$0" 2>&1 | tee -a "$LOG_FILE"
  fi
  status=${PIPESTATUS[0]}
  exit "$status"
fi

echo
echo "=== sync-agents run: $(date '+%Y-%m-%d %H:%M:%S %Z') ==="
echo "Mode: $([[ "$DRY_RUN" -eq 1 ]] && echo dry-run || echo apply), clean: $CLEAN"

[[ -d "$SOURCE_DIR" ]] || { echo "ERROR: $SOURCE_DIR not found"; exit 1; }

HARNESS_NAMES=(claude gemini opencode)
TARGET_DIRS=(
  "$PROJECT_ROOT/.claude/agents"
  "$PROJECT_ROOT/.gemini/agents"
  "$PROJECT_ROOT/.opencode/agents"
)
CODEX_DIR="$PROJECT_ROOT/.codex/agents"

declare -a AGENT_FILES=()
declare -a AGENT_NAMES=()
warnings=0
errors=0
linked=0
unchanged=0
removed=0
skipped=0
codex_planned=0

while IFS= read -r -d '' file; do
  filename="$(basename "$file" .md)"
  parent="$(basename "$(dirname "$file")")"

  if [[ "$(dirname "$file")" == "$SOURCE_DIR" ]]; then
    [[ "$filename" == "agents-catalog" || "$filename" == "README" ]] && continue
  elif [[ "$parent" != "$filename" ]]; then
    continue
  fi

  for existing_name in "${AGENT_NAMES[@]:-}"; do
    if [[ "$existing_name" == "$filename" ]]; then
      echo "ERROR: duplicate agent name '$filename' includes $file"
      errors=$((errors + 1))
      continue 2
    fi
  done

  if ! head -n 1 "$file" | grep -qx -- '---'; then
    echo "WARNING: skipping $file because it has no YAML frontmatter"
    warnings=$((warnings + 1))
    skipped=$((skipped + 1))
    continue
  fi

  declared_name="$(sed -n '/^---$/,/^---$/s/^name:[[:space:]]*//p' "$file" | head -n 1)"
  declared_name="${declared_name#\"}"
  declared_name="${declared_name%\"}"
  declared_name="${declared_name#\'}"
  declared_name="${declared_name%\'}"
  if [[ -z "$declared_name" || "$declared_name" != "$filename" ]]; then
    echo "ERROR: $file declares name '${declared_name:-<missing>}' but filename requires '$filename'"
    errors=$((errors + 1))
    continue
  fi

  AGENT_NAMES+=("$filename")
  AGENT_FILES+=("$file")
done < <(find "$SOURCE_DIR" -type f -name '*.md' -print0 | sort -z)

if [[ "$errors" -gt 0 ]]; then
  echo "FAILED: $errors canonical discovery error(s); no targets changed."
  exit 1
fi

echo "Discovered canonical agents: ${#AGENT_FILES[@]}"

for target in "${TARGET_DIRS[@]}" "$CODEX_DIR"; do
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "DRY-RUN mkdir -p ${target#$PROJECT_ROOT/}"
  else
    mkdir -p "$target"
  fi
done

if [[ "$CLEAN" -eq 1 ]]; then
  for target in "${TARGET_DIRS[@]}"; do
    [[ -d "$target" ]] || continue
    while IFS= read -r -d '' entry; do
      [[ -L "$entry" ]] || continue
      resolved="$(cd "$(dirname "$entry")" && realpath "$(readlink "$entry")" 2>/dev/null || true)"
      [[ "$resolved" == "$SOURCE_DIR"/* ]] || continue
      echo "$([[ "$DRY_RUN" -eq 1 ]] && echo DRY-RUN || echo REMOVE) ${entry#$PROJECT_ROOT/}"
      if [[ "$DRY_RUN" -eq 0 ]]; then
        rm -f "$entry"
      fi
      removed=$((removed + 1))
    done < <(find "$target" -maxdepth 1 -type l -print0)
  done

  if [[ -d "$CODEX_DIR" ]]; then
    while IFS= read -r -d '' entry; do
      if ! grep -Fqx "$CODEX_GENERATED_MARKER" "$entry" \
        && ! grep -Fqx "$CODEX_LEGACY_MARKER" "$entry"; then
        continue
      fi
      echo "$([[ "$DRY_RUN" -eq 1 ]] && echo DRY-RUN || echo REMOVE) ${entry#$PROJECT_ROOT/}"
      if [[ "$DRY_RUN" -eq 0 ]]; then
        rm -f "$entry"
      fi
      removed=$((removed + 1))
    done < <(find "$CODEX_DIR" -maxdepth 1 -type f -name '*.toml' -print0)
  fi
fi

for file in "${AGENT_FILES[@]}"; do
  name="$(basename "$file" .md)"
  for i in "${!HARNESS_NAMES[@]}"; do
    harness="${HARNESS_NAMES[$i]}"
    target_dir="${TARGET_DIRS[$i]}"
    destination="$target_dir/$name.md"
    relative_source="$(python3 -c 'import os,sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))' "$file" "$target_dir")"

    if [[ -L "$destination" ]]; then
      current="$(readlink "$destination")"
      if [[ "$current" == "$relative_source" ]]; then
        echo "OK      $harness/$name"
        unchanged=$((unchanged + 1))
      else
        echo "WARNING: skip ${destination#$PROJECT_ROOT/}; symlink points to '$current', expected '$relative_source'"
        warnings=$((warnings + 1))
        skipped=$((skipped + 1))
      fi
      continue
    fi

    if [[ -e "$destination" ]]; then
      echo "WARNING: skip ${destination#$PROJECT_ROOT/}; manually maintained path already exists"
      warnings=$((warnings + 1))
      skipped=$((skipped + 1))
      continue
    fi

    if [[ "$DRY_RUN" -eq 1 ]]; then
      echo "DRY-RUN LINK ${destination#$PROJECT_ROOT/} -> $relative_source"
    else
      ln -s "$relative_source" "$destination"
      echo "LINK    ${destination#$PROJECT_ROOT/} -> $relative_source"
    fi
    linked=$((linked + 1))
  done
  codex_planned=$((codex_planned + 1))
done

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "DRY-RUN CODEX: generate $codex_planned TOML adapter(s) with $CODEX_GENERATOR"
else
  if [[ ! -x "$CODEX_GENERATOR" ]]; then
    echo "ERROR: Codex generator is missing or not executable: $CODEX_GENERATOR"
    errors=$((errors + 1))
  elif ! (cd "$PROJECT_ROOT" && "$CODEX_GENERATOR"); then
    echo "ERROR: Codex adapter generation failed"
    errors=$((errors + 1))
  fi
fi

echo "Summary: discovered=${#AGENT_FILES[@]} linked=$linked unchanged=$unchanged removed=$removed skipped=$skipped warnings=$warnings errors=$errors codex=$codex_planned"
echo "Log: $LOG_FILE"

if [[ "$errors" -gt 0 || "$skipped" -gt 0 ]]; then
  exit 1
fi
