Account: diegosfb@gmail.com
Project ID: bettertris
Region: us-central1
Service Name: battletris-server-dev
Target Architecture: linux/amd64
Repository: https://github.com/diegosfb/BetterTris-v2
Artifact Registry Repo: battletris-images
Application Image: battletris-server
Tag: latest
Deployment URL: https://battletris-server-dev-435080045459.us-central1.run.app
Platform: GCP
Service Type: CloudRun
